# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre-merge:
    # Name of test
    name: Molecule
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install conftest and add to path
        run: |
         LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
         ARCH=$(arch)
         SYSTEM=$(uname)
         wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz"
         tar xzf conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz && echo "Extracted conftest tar archive"
         echo "$PWD/conftest" >> $GITHUB_PATH


      - name: Running Open Policy Agent test
        run: |
          source $GITHUB_PATH
          cd $GITHUB_WORKSPACE
          echo "----------------------"
          echo "Running linting"
          echo "----------------------"
          for playbook in $(ls *.yml)
          do
            echo "Running conftest on: $playbook"
            conftest test $playbook
          done
